stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  image: docker
  services:
    - docker:dind
  variables:
    PROD_DB_PASS: $REAL_PROD_DB_PASS
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t ${CI_REGISTRY}/lightbase/lightbot-backend/api:latest -t ${CI_REGISTRY}/lightbase/lightbot-backend/api:$CI_COMMIT_SHA .
    - docker push ${CI_REGISTRY}/lightbase/lightbot-backend/api:latest
    - docker push ${CI_REGISTRY}/lightbase/lightbot-backend/api:$CI_COMMIT_SHA

build_rasa:
  stage: build
  image: docker
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - cd rasa
    - docker build -t ${CI_REGISTRY}/lightbase/lightbot-backend/rasa:latest -t ${CI_REGISTRY}/lightbase/lightbot-backend/rasa:$CI_COMMIT_SHA .
    - docker push ${CI_REGISTRY}/lightbase/lightbot-backend/rasa:latest
    - docker push ${CI_REGISTRY}/lightbase/lightbot-backend/rasa:$CI_COMMIT_SHA

run_deploy:
  stage: deploy
  script:
    - curl -X POST -F token=${TOKEN} -F ref=master -F "variables[DEPLOY]=lightbot" https://gitlab.com/api/v4/projects/12436284/trigger/pipeline

